### ISSUE TITLE
Millumin 3

### ISSUE THREAD

**Issue by twelftree** [bitfocus/companion-module-anomes-millumin#3]
An update to the Millumin 2 module to support Millumin 3 would be very usfull

**Comment by Opgenorth** [comment]
Yes Please!  Just ordered a Stream Deck XL and need to integrate Millumin3 with switcher etc.

**Comment by JeffreyDavidsz** [comment]
So i'm currently building some actions and testing it in Millumin 3. It works as far as I can see. Doesn't work for you guys?

**Comment by cipi1965** [comment]
Closing this as the module works for Millumin 3/4
