### ISSUE TITLE
Issues with current 2.1.1 build talking to Millumin3

### ISSUE THREAD

**Issue by lotech** [bitfocus/companion-module-anomes-millumin#5]
Just a note that there seems to be issues with Millumin 3 and the current 2.1.1 build (probably earlier builds too).
Communication on my CompanionPi setup is working - I can rewind timelines and go next and back on cues in the dashboard and also receive feedback of which column I'm on. 
Things that don't work - Time remaining feedback and play/pause on a timeline don't.

**Comment by ethan-tripp** [comment]
+1 for remaining time remaining feedback not functioning. 
Millumin 3.18.e
Companion experimental build v2.2.0-91c9a35-2845

**Comment by cipi1965** [comment]
It should be fixed now
