### ISSUE TITLE
BUG: Cannot add multiple connections without ERROR

### ISSUE THREAD

**Issue by E2SLLC** [bitfocus/companion-module-anomes-millumin#6]
Adding a 2nd connection (in order to trigger a backup machine from the same cues) does not work.  After adding the 2nd connection, it will hang on Connecting.  Subsequently disabling and enabling the connection will immediately return an ERROR status.

One other wrinkle is that the 2nd machine is reacting to the cues.

**Comment by cipi1965** [comment]
For this to work you need to change receiving port
