### ISSUE TITLE
Companion Module Request (Millumin 4)

### ISSUE THREAD

**Issue by djslacker** [bitfocus/companion-module-anomes-millumin#7]
Hello, this is my first request so feel free to correct me if needed.

I am wondering if it would be possible to add a feature to Millumin's connection where you can get Millumin to display its Active Column  in a Stream Deck button.

**Comment by X21de** [comment]
Yes,

same issue here.
Maybe the module is no longer supported?

**Comment by djslacker** [comment]
The feature is actually on Companion 2.2.3.  I found it last night.
