### ISSUE TITLE
Feedback variables

### ISSUE THREAD

**Issue by mbialystock** [bitfocus/companion-module-anomes-millumin#8]
Looking for support to get the feedback variable for time remaining working correctly in Millumin 4 and Companion 2.4.2. It appears that the remaining time is only reported in seconds and does not clear when the media is cleared?

**Comment by mbialystock** [comment]
remaining time is only reported in seconds and does not clear when the media is cleared?

**Comment by JeffreyDavidsz** [comment]
No problem, I don't use Millumin nor I have a license for it. As far as I can see the module listen to `/millumin/layer:xxx/media/time`. The value that is returned is rounded up. That variable will keep the latest value. I can look into it, but I think i might need a license for it. The module needs to be converted to v3 also. If you have any funds available for it let me know.

**Comment by mbialystock** [comment]
Hi @JeffreyDavidsz, thanks for the quick reply and once over. 
Pretty sure Millumin's demo state is fully functional and completely free for 30 days. 
Ideally, I'd like it to feed back remaining time in 00:00:00 format(s), not just seconds, and remain on zeros after each clip plays out/when nothing is rolling.
Pardon any ignorance on my part, I'm just wading into these waters for the first time. In general I'm without real development money to throw at anything but what would typical funds look like for an update like this?

**Comment by cipi1965** [comment]
@mbialystock done, it will be available in next release
